name: python-mini-projet
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyterlab
    - ipywidgets
    - biopython
